import streamlit as st
import tempfile
import os
from pipeline import run_pipeline

# ── Page Config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="AI Meeting Notes Generator",
    page_icon="🎙️",
    layout="wide"
)

# ── Header ────────────────────────────────────────────────────────────────────

st.title("🎙️ AI Meeting Notes Generator")
st.markdown("Upload a meeting recording and get structured notes, action items, and a summary — automatically.")
st.divider()

# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.header("⚙️ Settings")
    
    whisper_model = st.selectbox(
        "Whisper Model",
        options=["tiny", "base", "small", "medium", "large"],
        index=3,  # medium by default
        help="Larger = more accurate but slower"
    )

    language = st.selectbox(
    "Audio Language",
    options=["Auto Detect", "English", "Hindi", "Marathi", "Spanish", "French", "German", "Arabic", "Chinese", "Japanese", "Portuguese"],
    index=0,
    help="Select the language spoken in the recording"
)
    
    st.markdown("---")
    st.markdown("**Model Info**")
    st.markdown("- 🎙️ Whisper — transcription")
    st.markdown("- 🧹 Llama 3.1 8B — cleanup")
    st.markdown("- ✅ Llama 3.1 8B — action items")
    st.markdown("- 📋 Llama 3.1 8B — summary")
    
    st.markdown("---")
    st.markdown("**Supported Formats**")
    st.markdown("mp3, wav, m4a, ogg, flac")

# ── File Upload ───────────────────────────────────────────────────────────────

uploaded_file = st.file_uploader(
    "Upload your meeting recording",
    type=["mp3", "wav", "m4a", "ogg", "flac"],
    help="Max file size depends on your system memory"
)

if uploaded_file:
    st.audio(uploaded_file, format=f"audio/{uploaded_file.name.split('.')[-1]}")
    st.success(f"✅ File uploaded: {uploaded_file.name} ({round(uploaded_file.size / 1024 / 1024, 2)} MB)")

# ── Run Pipeline ──────────────────────────────────────────────────────────────

if uploaded_file:
    if st.button("🚀 Generate Meeting Notes", type="primary", use_container_width=True):
        
        # Save uploaded file to a temp location
        with tempfile.NamedTemporaryFile(delete=False, suffix=f".{uploaded_file.name.split('.')[-1]}") as tmp:
            tmp.write(uploaded_file.read())
            tmp_path = tmp.name
        
        try:
            # Progress indicators
            with st.status("Running AI pipeline...", expanded=True) as status:
                
                st.write("🎙️ Model 1: Transcribing audio with Whisper...")
                
                # Patch pipeline to use selected whisper model
                import pipeline
                pipeline.WHISPER_MODEL = whisper_model
                
                results = run_pipeline(tmp_path, language=language)
                
                st.write("🧹 Model 2: Cleaning transcript...")
                st.write("✅ Model 3: Extracting action items...")
                st.write("📋 Model 4: Generating summary...")
                status.update(label="✅ Pipeline complete!", state="complete")
            
            st.divider()
            
            # ── Results in Tabs ────────────────────────────────────────────
            
            tab1, tab2, tab3, tab4 = st.tabs([
                "📋 Summary",
                "✅ Action Items", 
                "🧹 Cleaned Transcript",
                "🎙️ Raw Transcript"
            ])
            
            with tab1:
                st.markdown(results["summary"])
            
            with tab2:
                st.markdown(results["action_items"])
            
            with tab3:
                st.markdown(results["clean_transcript"])
            
            with tab4:
                st.text(results["raw_transcript"])
            
            st.divider()
            
            # ── Download Button ────────────────────────────────────────────
            
            full_notes = f"""# Meeting Notes
Generated by AI Meeting Notes Generator

---

## Executive Summary

{results["summary"]}

---

## Action Items

{results["action_items"]}

---

## Cleaned Transcript

{results["clean_transcript"]}

---

## Raw Transcript

{results["raw_transcript"]}
"""
            
            st.download_button(
                label="⬇️ Download Full Notes",
                data=full_notes,
                file_name=f"meeting_notes_{uploaded_file.name.split('.')[0]}.md",
                mime="text/markdown",
                use_container_width=True
            )
        
        except Exception as e:
            st.error(f"❌ Pipeline failed: {str(e)}")
            st.exception(e)
        
        finally:
            # Clean up temp file
            os.unlink(tmp_path)

else:
    # Empty state
    st.info("👆 Upload an audio file to get started")
    
    with st.expander("How it works"):
        st.markdown("""
        1. **Upload** your meeting recording (mp3, wav, m4a, ogg, flac)
        2. **Click** Generate Meeting Notes
        3. The pipeline runs 4 AI models in sequence:
           - Whisper transcribes your audio to text
           - Llama cleans up the raw transcript
           - Llama extracts all action items with owners and deadlines
           - Llama generates a structured executive summary
        4. **Download** your notes as a markdown file
        """)